# Generated by Django 4.2.2 on 2023-07-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('ID_usuario', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
                ('img', models.FileField(upload_to='img/', verbose_name='img')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
